<?php

namespace Modules\Equipment\Controllers;

use App\Notifications\AdminChannelServices;
use Modules\Booking\Equipment\BookingUpdatedEquipment;
use Modules\Core\Equipment\CreatedServicesEquipment;
use Modules\Core\Equipment\UpdatedServiceEquipment;
use Modules\Equipment\Exports\EquipmentExport;
use Modules\Equipment\Models\Equipment;
use Modules\Equipment\Models\EquipmentTranslation;
use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Booking\Models\Booking;
use Modules\Location\Models\LocationCategory;
use Modules\Location\Services\LocationService;

class VendorEquipmentController extends FrontendController
{
    protected $equipmentClass;
    protected $equipmentTranslationClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;
    /**
     * @var string
     */
    private $locationCategoryClass;

    public function __construct()
    {
        parent::__construct();
        $this->equipmentClass = Equipment::class;
        $this->equipmentTranslationClass = EquipmentTranslation::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->locationCategoryClass = LocationCategory::class;
        $this->bookingClass = Booking::class;
    }

    public function callAction($method, $parameters)
    {
        if (!Equipment::isEnable()) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function indexEquipment(Request $request)
    {
        $this->checkPermission('equipment_manage');
        $user_id = Auth::id();
        $list_tour = $this->equipmentClass::where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'breadcrumbs' => [
                [
                    'name' => __('Manage equipments'),
                    'url' => route('equipment.vendor.index')
                ],
                [
                    'name' => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title' => __("Manage equipments"),
        ];
        return view('Equipment::frontend.vendorEquipment.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('equipment_manage');
        $user_id = Auth::id();
        $list_tour = $this->equipmentClass::onlyTrashed()->where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'recovery' => 1,
            'breadcrumbs' => [
                [
                    'name' => __('Manage equipments'),
                    'url' => route('equipment.vendor.index')
                ],
                [
                    'name' => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title' => __("Recovery equipments"),
        ];
        return view('Equipment::frontend.vendorEquipment.index', $data);
    }

    public function restore($id)
    {
        $this->checkPermission('equipment_manage');
        $user_id = Auth::id();
        $query = $this->equipmentClass::onlyTrashed()->where("create_user", $user_id)->where("id", $id)->first();
        if (!empty($query)) {
            $query->restore();
        }
        return redirect(route('equipment.vendor.recovery'))->with('success', __('Restore event success!'));
    }

    public function createEquipment(Request $request)
    {
        $this->checkPermission('equipment_manage');
        $row = new $this->equipmentClass();
        $data = [
            'row' => $row,
            'translation' => new $this->equipmentTranslationClass(),
            'equipment_location' => $this->locationClass::where("status", "publish")->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'attributes' => $this->attributesClass::where('service', 'equipment')->get(),
            'breadcrumbs' => [
                [
                    'name' => __('Manage equipments'),
                    'url' => route('equipment.vendor.index')
                ],
                [
                    'name' => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title' => __("Create equipments"),
        ];
        return view('Equipment::frontend.vendorEquipment.detail', $data);
    }


    public function store(Request $request, LocationService $locationService, $id)
    {
        if ($id > 0) {
            $this->checkPermission('equipment_manage');
            $row = $this->equipmentClass::find($id);
            if (empty($row)) {
                return redirect(route('equipment.vendor.index'));
            }

            if ($row->create_user != Auth::id() and !$this->hasPermission('equipment_manage_others')) {
                return redirect(route('equipment.vendor.index'));
            }
        } else {
            $this->checkPermission('equipment_manage');
            $row = new $this->equipmentClass();
            $row->status = "publish";
            if (setting_item("equipment_vendor_create_service_must_approved_by_admin", 0)) {
                $row->status = "pending";
            }
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'duration',
            'start_time',
            'price',
            'sale_price',
            'ticket_types',
            'enable_extra_price',
            'extra_price',
            'is_featured',
            'default_state',
            'enable_service_fee',
            'service_fee',
            'surrounding',
        ];
        if ($this->hasPermission('equipment_manage_others')) {
            $dataKeys[] = 'create_user';
        }
        $row->location_id = $locationService->store($request);

        $row->fillByAttr($dataKeys, $request->input());

        $res = $row->saveOriginOrTranslation($request->input('lang'), true);

        if ($res) {
            if ($id > 0) {
                event(new UpdatedServiceequipment($row));

                return back()->with('success', __('Your equipment post has been updated'));
            } else {
                event(new CreatedServicesequipment($row));
                return redirect(route('equipment.vendor.edit', ['id' => $row->id]))->with('success', __('Your equipment post has been created'));
            }
        }
    }

    public function editEquipment(Request $request, $id)
    {
        $this->checkPermission('equipment_manage');
        $user_id = Auth::id();
        $row = $this->equipmentClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('equipment.vendor.index'))->with('warning', __('equipment not found!'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        $data = [
            'translation' => $translation,
            'row' => $row,
            'equipment_location' => $this->locationClass::where("status", "publish")->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'attributes' => $this->attributesClass::where('service', 'equipment')->get(),
            'breadcrumbs' => [
                [
                    'name' => __('Manage equipments'),
                    'url' => route('equipment.vendor.index')
                ],
                [
                    'name' => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title' => __("Edit equipments"),
        ];
        return view('Equipment::frontend.vendorEquipment.detail', $data);
    }

    public function deleteEquipment($id)
    {
        $this->checkPermission('equipment_manage');
        $user_id = Auth::id();
        if (\request()->query('permanently_delete')) {
            $query = $this->equipmentClass::where("create_user", $user_id)->where("id", $id)->withTrahsed()->first();
            if (!empty($query)) {
                $query->forceDelete();
            }
        } else {
            $query = $this->equipmentClass::where("create_user", $user_id)->where("id", $id)->first();
            if (!empty($query)) {
                $query->delete();
                event(new UpdatedServiceequipment($query));
            }
        }
        return redirect(route('equipment.vendor.index'))->with('success', __('Delete event success!'));
    }

    public function bulkEditEquipment($id, Request $request)
    {
        $this->checkPermission('equipment_manage');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->equipmentClass::where("create_user", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if (empty($query)) {
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action) {
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                break;
        }
        $query->save();
        event(new UpdatedServiceequipment($query));

        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReportBulkEdit($booking_id, Request $request)
    {
        $status = $request->input('status');
        if (!empty(setting_item("equipment_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if (!empty($item)) {
                $item->status = $status;
                $item->save();

                if ($status == Booking::CANCELLED) $item->tryRefundToWallet();

                event(new BookingUpdatedequipment($item));
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }

    public function equipmentExport()
    {
        $this->checkPermission('equipment_manage');

        return (new EquipmentExport())->download('equipment-' . date('M-d-Y') . '.xlsx');
    }
}
