<?php


namespace Modules\User\Models;


use App\BaseModel;
use Illuminate\Database\Eloquent\Model;

/**
 * @property string name
 * @property string slug
 * @property string value
 */
class PlanFeature extends BaseModel
{
    const JOB_CREATE = 'job-create';
    const JOB_SPONSORED = 'job-sponsored';

    const ANNOUNCEMENT_CREATE = 'announcement-create';
    const ANNOUNCEMENT_SPONSORED = 'announcement-sponsored';
    public const CHAT_ACCESS = 'chat-access';
    public const SUB_ACCOUNTS = 'sub-accounts';

    public const FEATURES = [
        self::JOB_CREATE             => 'Job Posting',
        self::JOB_SPONSORED          => 'Popular job posts',
        self::ANNOUNCEMENT_CREATE    => 'Announcement Posting',
        self::ANNOUNCEMENT_SPONSORED => 'Popular Announcement posts',
        self::CHAT_ACCESS            => 'Chat access',
        self::SUB_ACCOUNTS           => 'Employee accounts'
    ];

    protected $table  = 'bc_plan_features';
    protected $fillable = ['name', 'slug', 'value'];

    public function plan()
    {
        return $this->belongsTo(Plan::class,'plan_id');
    }

    public function save(array $options = [])
    {
        return Model::save($options); // TODO: Change the autogenerated stub
    }
}
