<?php

namespace Modules\Equipment\Admin;

use Illuminate\Http\Request;
use Modules\AdminController;
use Modules\Equipment\Models\Equipment;
use Modules\Core\Models\Attributes;
use Modules\Core\Models\AttributesTranslation;

class AttributeController extends AdminController
{
    protected $attributesClass;
    protected $termsClass;

    public function __construct()
    {
        $this->setActiveMenu(route('equipment.admin.index'));
        parent::__construct();
        $this->attributesClass = Attributes::class;
    }

    public function callAction($method, $parameters)
    {
        if (!Equipment::isEnable()) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $this->checkPermission('equipment_manage_others');
        $listAttr = $this->attributesClass::where("service", 'equipment');
        if (!empty($search = $request->query('s'))) {
            $listAttr->where('name', 'LIKE', '%' . $search . '%');
        }
        $listAttr->orderBy('created_at', 'desc');
        $data = [
            'rows' => $listAttr->get(),
            'row' => new $this->attributesClass(),
            'translation' => new AttributesTranslation(),
            'breadcrumbs' => [
                [
                    'name' => __('equipment'),
                    'url' => route('equipment.admin.index')
                ],
                [
                    'name' => __('Attributes'),
                    'class' => 'active'
                ],
            ]
        ];
        return view('Equipment::admin.attribute.index', $data);
    }

    public function edit(Request $request, $id)
    {
        $row = $this->attributesClass::find($id);
        if (empty($row)) {
            return redirect()->back()->with('error', __('Attributes not found!'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        $this->checkPermission('equipment_manage_others');
        $data = [
            'translation' => $translation,
            'enable_multi_lang' => true,
            'rows' => $this->attributesClass::where("service", 'equipment')->get(),
            'row' => $row,
            'breadcrumbs' => [
                [
                    'name' => __('equipment'),
                    'url' => route('equipment.admin.index')
                ],
                [
                    'name' => __('Attributes'),
                    'url' => route('equipment.admin.attribute.index')
                ],
                [
                    'name' => __('Attribute: :name', ['name' => $row->name]),
                    'class' => 'active'
                ],
            ]
        ];
        return view('Equipment::admin.attribute.detail', $data);
    }

    public function store(Request $request)
    {
        $this->checkPermission('equipment_manage_others');
        $this->validate($request, [
            'name' => 'required'
        ]);
        $id = $request->input('id');
        if ($id) {
            $row = $this->attributesClass::find($id);
            if (empty($row)) {
                return redirect()->back()->with('error', __('Attributes not found!'));
            }
        } else {
            $row = new $this->attributesClass($request->input());
            $row->service = 'equipment';
        }
        $row->fill($request->input());
        $res = $row->saveOriginOrTranslation($request->input('lang'));
        if ($res) {
            return redirect()->back()->with('success', __('Attribute saved'));
        }
    }

    public function editAttrBulk(Request $request)
    {
        $this->checkPermission('equipment_manage_others');
        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('Select at least 1 item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Select an Action!'));
        }
        if ($action == "delete") {
            foreach ($ids as $id) {
                $query = $this->attributesClass::where("id", $id);
                $query->first();
                if (!empty($query)) {
                    $query->delete();
                }
            }
        }
        return redirect()->back()->with('success', __('Updated success!'));
    }

    public function getForSelect2(Request $request)
    {
        $pre_selected = $request->query('pre_selected');
        $selected = $request->query('selected');

        if ($pre_selected && $selected) {
            if (is_array($selected)) {
                $query = $this->termsClass::getForSelect2Query('equipment');
                $items = $query->whereIn('bc_terms.id', $selected)->take(50)->get();
                return response()->json([
                    'items' => $items
                ]);
            }

            if (empty($item)) {
                return response()->json([
                    'text' => ''
                ]);
            } else {
                return response()->json([
                    'text' => $item->name
                ]);
            }
        }
        $q = $request->query('q');
        $query = $this->termsClass::getForSelect2Query('equipment', $q);
        $res = $query->orderBy('bc_terms.id', 'desc')->limit(20)->get();
        return response()->json([
            'results' => $res
        ]);
    }
}
