<?php


namespace Modules\User\Models;


use App\BaseModel;
use Illuminate\Database\Eloquent\Model;

class PlanFeature extends BaseModel
{
    const JOB_CREATE = 'job-create';
    const JOB_SPONSORED = 'job-sponsored';
    const EQUIPMENT_CREATE = 'equipment-create';
    const EQUIPMENT_SPONSORED = 'equipment-sponsored';

    const FEATURES = [
        self::JOB_CREATE => 'Job Posting',
        self::JOB_SPONSORED => 'Sponsored job posts',
        self::EQUIPMENT_CREATE => 'Equipment Posting',
        self::EQUIPMENT_SPONSORED => 'Sponsored equipment posts'
    ];
    protected $table  = 'bc_plan_features';
    protected $fillable = ['name', 'slug', 'value'];

    public function plan()
    {
        return $this->belongsTo(Plan::class,'plan_id');
    }

    public function save(array $options = [])
    {
        return Model::save($options); // TODO: Change the autogenerated stub
    }
}
