<?php

namespace Database\Seeders;

use App\Models\CellGripperRequirement;
use App\Models\PalletizerModule;
use Illuminate\Database\Seeder;

class CellGripperRequirementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ## FORK INFEED LEFT PUSH
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id,'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ## FORK INFEED RIGHT PUSH
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'fork-gripper')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ## SINGLE VACUUM TOOL INFEED LEFT PUSH
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id,'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ## SINGLE VACUUM TOOL INFEED RIGHT PUSH
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ## SINGLE VACUUM TOOL INFEED LEFT
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ## SINGLE VACUUM TOOL INFEED RIGHT
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-single')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ## DUAL VACUUM TOOL INFEED LEFT PUSH
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id,'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ## DUAL VACUUM TOOL INFEED RIGHT PUSH
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'center-right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ## DUAL VACUUM TOOL INFEED LEFT
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-straight-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'left-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ## DUAL VACUUM TOOL INFEED RIGHT
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-floor-pallet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-straight-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-guarding-only')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-u-turn-pallet-conveyor')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-slip-sheet')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-slip-sheet')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],

            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-floor-pallet')->first()->id],
            ['gripper_id' => PalletizerModule::where('slug', '=', 'vacuum-gripper-double')->first()->id, 'infeed_id' => PalletizerModule::where('slug', '=', 'right-infeed')->first()->id, 'left_side_id' => PalletizerModule::where('slug', '=', 'left-side-guarding-only')->first()->id, 'right_side_id' => PalletizerModule::where('slug', '=', 'right-side-u-turn-pallet-conveyor')->first()->id],
        ];

        foreach ($data as $item) {
            CellGripperRequirement::create($item);
        }
    }
}
